apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-no-request-cpu
  namespace: test-namespace
spec:
  containers:
    - name: data-loader
      image: scratch
      resources:
        requests:
          memory: 128Mi
        limits:
          cpu: 2
          memory: 256Mi
